spring.application.name=tc02

spring.datasource.url=${SPRING_DATASOURCE_URL:${DATASOURCE_URL}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DATABASE_USER}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSW}}

spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

api.security.token.secret=${SPRING_JWT_SECRET:${SPRING_KEY_JWT_SECRET}}