spring.application.name=tc01
spring.datasource.url=jdbc:postgresql://localhost:5432/Fiap-tc01
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

api.security.token.secret=${JWT_SECRET:api-secret}