spring.application.name=tc01
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Fiap-tc01}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345678}

spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

api.security.token.secret=${SPRING_JWT_SECRET:api-secret}